export const types = {
	SET_QUERY: 'SET_QUERY',
	SET_PICTURES: 'SET_PICTURES',
	SET_PICTURES_RESET: 'SET_PICTURES_RESET',
	SET_LOADING: 'SET_LOADING',
	SET_PAGE: 'SET_PAGE',
	SET_IS_OPEN: 'SET_IS_OPEN',
	SET_CURRENT_IMG: 'SET_CURRENT_IMG',
	SET_CURRENT_ALT: 'SET_CURRENT_ALT',
}
